export const GET_SERVICEFEES_INFO_LOADING = 'GET_SERVICEFEES_INFO_LOADING'
export const GET_SERVICEFEES_INFO_SUCCESS = 'GET_SERVICEFEES_INFO_SUCCESS'
export const GET_SERVICEFEES_INFO_FAILURE = 'GET_SERVICEFEES_INFO_FAILURE'

export const ADD_SERVICEFEE_INFO_LOADING = 'ADD_SERVICEFEE_INFO_LOADING'
export const ADD_SERVICEFEE_INFO_SUCCESS = 'ADD_SERVICEFEE_INFO_SUCCESS'
export const ADD_SERVICEFEE_INFO_FAILURE = 'ADD_SERVICEFEE_INFO_FAILURE'

export const UPDATE_SERVICEFEE_INFO_LOADING = 'UPDATE_SERVICEFEE_INFO_LOADING'
export const UPDATE_SERVICEFEE_INFO_FAILURE = 'UPDATE_SERVICEFEE_INFO_FAILURE'
export const UPDATE_SERVICEFEE_INFO_SUCCESS = 'UPDATE_SERVICEFEE_INFO_SUCCESS'