export const GET_WEDDINGS_INFO_LOADING = 'GET_WEDDINGS_INFO_LOADING'
export const GET_WEDDINGS_INFO_SUCCESS = 'GET_WEDDINGS_INFO_SUCCESS'
export const GET_WEDDINGS_INFO_FAILURE = 'GET_WEDDINGS_INFO_FAILURE'

export const ADD_WEDDING_INFO_LOADING = 'ADD_WEDDING_INFO_LOADING'
export const ADD_WEDDING_INFO_SUCCESS = 'ADD_WEDDING_INFO_SUCCESS'
export const ADD_WEDDING_INFO_FAILURE = 'ADD_WEDDING_INFO_FAILURE'

export const UPDATE_WEDDING_INFO_LOADING = 'UPDATE_WEDDING_INFO_LOADING'
export const UPDATE_WEDDING_INFO_SUCCESS = 'UPDATE_WEDDING_INFO_SUCCESS'
export const UPDATE_WEDDING_INFO_FAILURE = 'UPDATE_WEDDING_INFO_FAILURE'