export const GET_PROFILE_INFO_LOADING = 'GET_PROFILE_INFO_LOADING'
export const GET_PROFILE_INFO_SUCCESS = 'GET_PROFILE_INFO_SUCCESS'
export const GET_PROFILE_INFO_FAILURE = 'GET_PROFILE_INFO_FAILURE'