export const GET_EXPENSES_INFO_LOADING = 'GET_EXPENSES_INFO_LOADING'
export const GET_EXPENSES_INFO_SUCCESS = 'GET_EXPENSES_INFO_SUCCESS'
export const GET_EXPENSES_INFO_FAILURE = 'GET_EXPENSES_INFO_FAILURE'

export const ADD_EXPENSE_INFO_LOADING = 'ADD_EXPENSE_INFO_LOADING'
export const ADD_EXPENSE_INFO_SUCCESS = 'ADD_EXPENSE_INFO_SUCCESS'
export const ADD_EXPENSE_INFO_FAILURE = 'ADD_EXPENSE_INFO_FAILURE'

export const UPDATE_EXPENSE_INFO_LOADING = 'UPDATE_EXPENSE_INFO_LOADING'
export const UPDATE_EXPENSE_INFO_SUCCESS = 'UPDATE_EXPENSE_INFO_SUCCESS'
export const UPDATE_EXPENSE_INFO_FAILURE = 'UPDATE_EXPENSE_INFO_FAILURE'

export const DELETE_EXPENSE_INFO_LOADING = 'DELETE_EXPENSE_INFO_LOADING'
export const DELETE_EXPENSE_INFO_SUCCESS = 'DELETE_EXPENSE_INFO_SUCCESS'
export const DELETE_EXPENSE_INFO_FAILURE = 'DELETE_EXPENSE_INFO_FAILURE'