export const GET_BAPTISMS_INFO_LOADING = 'GET_BAPTISMS_INFO_LOADING'
export const GET_BAPTISMS_INFO_SUCCESS = 'GET_BAPTISMS_INFO_SUCCESS'
export const GET_BAPTISMS_INFO_FAILURE = 'GET_BAPTISMS_INFO_FAILURE'

export const ADD_BAPTISM_INFO_LOADING = 'ADD_BAPTISM_INFO_LOADING'
export const ADD_BAPTISM_INFO_SUCCESS = 'ADD_BAPTISM_INFO_SUCCESS'
export const ADD_BAPTISM_INFO_FAILURE = 'ADD_BAPTISM_INFO_FAILURE'

export const UPDATE_BAPTISM_INFO_LOADING = 'UPDATE_BAPTISM_INFO_LOADING'
export const UPDATE_BAPTISM_INFO_SUCCESS = 'UPDATE_BAPTISM_INFO_SUCCESS'
export const UPDATE_BAPTISM_INFO_FAILURE = 'UPDATE_BAPTISM_INFO_FAILURE'