export const GET_ACTIVITIES_INFO_LOADING = 'GET_ACTIVITIES_INFO_LOADING'
export const GET_ACTIVITIES_INFO_SUCCESS = 'GET_ACTIVITIES_INFO_SUCCESS'
export const GET_ACTIVITIES_INFO_FAILURE = 'GET_ACTIVITIES_INFO_FAILURE'

export const ADD_ACTIVITY_INFO_LOADING = 'ADD_ACTIVITY_INFO_LOADING'
export const ADD_ACTIVITY_INFO_SUCCESS = 'ADD_ACTIVITY_INFO_SUCCESS'
export const ADD_ACTIVITY_INFO_FAILURE = 'ADD_ACTIVITY_INFO_FAILURE'

export const UPDATE_ACTIVITY_INFO_LOADING = 'UPDATE_ACTIVITY_INFO_LOADING'
export const UPDATE_ACTIVITY_INFO_SUCCESS = 'UPDATE_ACTIVITY_INFO_SUCCESS'
export const UPDATE_ACTIVITY_INFO_FAILURE = 'UPDATE_ACTIVITY_INFO_FAILURE'

export const DELETE_ACTIVITY_INFO_LOADING = 'DELETE_ACTIVITY_INFO_LOADING'
export const DELETE_ACTIVITY_INFO_SUCCESS = 'DELETE_ACTIVITY_INFO_SUCCESS'
export const DELETE_ACTIVITY_INFO_FAILURE = 'DELETE_ACTIVITY_INFO_FAILURE'